<?php
require_once('inc/init.inc.php');
// ------------- TRAITEMENT ---------------

// -------------- AFFICHAGE ---------------
require_once('inc/haut.inc.php');
?>
<h1>CONDITIONS GENERALES D'UTILISATIONS :</h1>

<p style="text-align:justify"><strong>Ce site n'a aucun but commercial. Il a été réalisé dans le cadre d'un projet d'étude de l'organisme de formation IFOCOP Paris XI.</strong></p>

<p style="text-align:justify">Les présentes conditions d'utilisations sont conclues d’une part par la société Le Bon Troc au capital social de XXXXX€ dont le siège social est situé à Paris, immatriculée au Registre du Commerce et des Sociétés de Paris sous le numéro XXXXXX ci-après dénommée "Le Bon Troc" et gérant le site Le Bon Troc, www.lebontroc.com  et, d’autre part, par toute personne physique ou morale souhaitant procéder à un achat via le site internet Le Bon Troc, www.lebontroc.com dénommée ci-après " l’utilisateur ".</p>

<p style="text-align:justify"><strong>Article 1. Objet</strong></p>
<p style="text-align:justify">Les présentes conditions d'utilisations visent à définir les relations contractuelles entre Le Bon Troc et l’utilisateur et les conditions applicables à tout achat effectué par le biais du site internet Le Bon Troc, www.lebontroc.com. L’acquisition d’un produit à travers le présent site implique une acceptation sans réserve par l’utilisateur des présentes conditions d'utilisations dont l’utilisateur reconnaît avoir pris connaissance préalablement à sa commande. Avant toute transaction, l’utilisateur déclare d’une part que l’achat de produits sur le site Le Bon Troc, www.lebontroc.com est sans rapport direct avec son activité professionnelle et est limité à une utilisation strictement personnelle et d’autre part avoir la pleine capacité juridique, lui permettant de s’engager au titre des présentes conditions générales de ventes.<br> 
La société Le Bon Troc conserve la possibilité de modifier à tout moment ces conditions d'utilisationss, afin de respecter toute nouvelle réglementation ou dans le but d'améliorer l’utilisation de son site. De ce fait, les conditions applicables seront celles en vigueur à la date de la commande par l’utilisateur.</p>

<p style="text-align:justify"><strong>Article 2. Produits</strong></p>
<p style="text-align:justify">Les produits proposés sont ceux qui figurent sur le site Le Bon Troc, www.lebontroc.com de la société Le Bon Troc, dans la limite des stocks disponibles. La société Le Bon Troc se réserve le droit de modifier à tout moment l’assortiment de produits. Chaque produit est présenté sur le site internet sous forme d’un descriptif reprenant ses principales caractéristiques techniques (contenance, utilisation, composition…). Les photographies sont les plus fidèles possibles mais n’engagent en rien le Vendeur. La vente des produits présentés dans le site Le Bon Troc, www.lebontroc.com est destinée à tous les utilisateurs résidants dans les pays qui autorisent pleinement l’entrée sur leur territoire de ces produits. (à modifier éventuellement)</p>

<p style="text-align:justify"><strong>Article 3. Tarifs</strong></p> 
<p style="text-align:justify">Les prix figurant sur les fiches produits du catalogue internet et sont des prix en Euros (€) toutes taxes comprises (TTC) tenant compte de la TVA applicable au jour de la commande. Tout changement du taux de la TVA pourra être répercuté sur le prix des produits. La société Le Bon Troc se réserve le droit de modifier ses prix à tout moment, étant toutefois entendu que le prix figurant au catalogue le jour de la commande sera le seul applicable à l’utilisateur. Les prix indiqués ne comprennent pas les frais de livraison, facturés en supplément du prix des produits achetés suivant le montant total de la commande. En France métropolitaine, pour toute commande supérieure ou égale à XXX euros TTC, les frais de port sont offerts ; pour toute commande inférieure à XXX euros TTC, un forfait de participation aux frais d’expédition sera facturé à l’utilisateur d'un montant de XXX euros TTC.</p>

<p style="text-align:justify"><strong>Article 4. Commande et modalités de paiement </strong></p>
<p style="text-align:justify">Avant toute commande, l’utilisateur doit créer un compte sur le site .Le Bon Troc, www.lebontroc.com. La rubrique de création de compte est accessible directement depuis la barre de menu latérale. A chaque visite, l’utilisateur, s’il souhaite commander ou consulter son compte (état des commandes, profil…), devra s’identifier à l’aide de ces informations. La société Le Bon Troc propose à l’utilisateur de commander et régler ses produits en plusieurs étapes, avec 3 options de paiement au choix :<br>
- Paiement par chèque : l’utilisateur sélectionne les produits qu’il souhaite commander dans le « panier », modifie si besoin (quantités, références…), vérifie l’adresse de livraison ou en renseigne une nouvelle. Puis, les frais de port sont calculés et soumis à l’utilisateur, ainsi que le nom du transporteur. Ensuite, l’utilisateur choisit le mode de paiement de son choix : « Paiement par chèque ». Enfin, la dernière étape lui propose de vérifier l’ensemble des informations, prendre connaissance et accepter les présentes conditions générales de vente en cochant la case correspondante, puis l’invite à valider sa commande en cliquant sur le bouton « Confirmer ma commande ». Ce dernier clic forme la conclusion définitive du contrat. Dès validation, l’utilisateur reçoit un bon de commande confirmant l’enregistrement de sa commande. Afin de finaliser son paiement et déclencher le traitement de sa commande, l’utilisateur doit imprimer ce bon de commande, accompagné de son chèque libellé à l’ordre de « Le Bon Troc » à l’adresse suivante : Le Bon Troc, 25 rue Mademoiselle, 75015, Paris, France. Aucun paiement en espèces ne doit être envoyé. Seuls les chèques émis par une banque française seront acceptés. Dès réception du chèque, la commande sera traitée et l’utilisateur en sera informé par email. La société Le Bon Troc expédiera les produits au plus tôt 2 jours ouvrés après encaissement du chèque correspondant à la commande, sous réserve de provisions.<br>
- Paiement par virement bancaire : l’utilisateur sélectionne les produits qu’il souhaite commander dans le « panier », modifie si besoin (quantités, références…), vérifie l’adresse de livraison ou en renseigne une nouvelle. Puis, les frais de port sont calculés et soumis à l’utilisateur, ainsi que le nom du transporteur. Ensuite, l’utilisateur choisit le mode de paiement de son choix : « Paiement par virement ». Enfin, la dernière étape lui propose de vérifier l’ensemble des informations, prendre connaissance et accepter les présentes conditions générales de vente en cochant la case correspondante, puis l’invite à valider sa commande en cliquant sur le bouton « Confirmer ma commande ». Ce dernier clic forme la conclusion définitive du contrat. Dès validation, l’utilisateur reçoit un bon de commande confirmant l’enregistrement de sa commande. Afin de finaliser son paiement et déclencher le traitement de sa commande, l’utilisateur doit contacter sa banque afin d'effectuer le virement correspondant au montant de sa commande vers le compte bancaire de Le Bon Troc, dont les coordonnées sont communiquées à l'utilisateur. Dès réception du virement, la commande sera traitée et l’utilisateur en sera informé par e-mail. La société Le Bon Troc expédiera les produits au plus tôt 2 jours ouvrés après réception du virement correspondant à la commande, sous réserve de provisions.<br>
- Paiement sécurisé par Paypal ou carte bancaire (via le système PAYPAL) : l’utilisateur sélectionne les produits qu’il souhaite commander dans le « panier », modifie si besoin (quantités, références…), vérifie l’adresse de livraison ou en renseigne une nouvelle. Puis, les frais de port sont calculés et soumis à l’utilisateur, ainsi que le nom du transporteur. Ensuite, l’utilisateur choisit le mode de paiement de son choix : « Paiement par Paypal ». L’étape suivante lui propose de vérifier l’ensemble des informations, prendre connaissance et accepter les présentes conditions générales de vente en cochant la case correspondante, puis l’invite à valider sa commande en cliquant sur le bouton « Confirmer ma commande ». Enfin, l’utilisateur est redirigé sur l’interface sécurisée PAYPAL afin de renseigner en toute sécurité ses références de compte Paypal ou de carte bleue personnelle. Si le paiement est accepté, la commande est enregistrée et le contrat définitivement formé. Le paiement par compte Paypal ou par carte bancaire est irrévocable. En cas d’utilisation frauduleuse de celle-ci, l’utilisateur pourra exiger l’annulation du paiement par carte, les sommes versées seront alors recréditées ou restituées. La responsabilité du titulaire d’une carte bancaire n’est pas engagée si le paiement contesté a été prouvé effectué frauduleusement, à distance, sans utilisation physique de sa carte. Pour obtenir le remboursement du débit frauduleux et des éventuels frais bancaires que l’opération a pu engendrer, le porteur de la carte doit contester, par écrit, le prélèvement auprès de sa banque, dans les 70 jours suivant l’opération, voire 120 jours si le contrat le liant à celle-ci le prévoit. Les montants prélevés sont remboursés par la banque dans un délai maximum d’un mois après réception de la contestation écrite formée par le porteur. Aucun frais de restitution des sommes ne pourra être mis à la charge du titulaire.<br>
La confirmation d’une commande entraîne acceptation des présentes conditions d'utilisations, la reconnaissance d’en avoir parfaite connaissance et la renonciation à se prévaloir de ses propres conditions d’achat. L’ensemble des données fournies et la confirmation enregistrée vaudront preuve de la transaction. Si l’utilisateur possède une adresse électronique et s’il l’a renseignée sur son bon de commande, la société Le Bon Troc lui communiquera par courrier électronique la confirmation de l’enregistrement de sa commande.<br>
Si l’utilisateur souhaite contacter la société Le Bon Troc, il peut le faire soit par courrier à l’adresse suivante : Le Bon Troc, 25 rue Mademoiselle, 75015, Paris, France ; soit par email à l’adresse suivante : admin@lebontroc.com , soit par téléphone au 0123456789.</p>
<p style="text-align:justify"><strong>Article 5. Réserve de propriété </strong></p>
<p style="text-align:justify">La société Le Bon Troc conserve la propriété pleine et entière des produits vendus jusqu'au parfait encaissement du prix, en principal, frais et taxes compris.</p>
<p style="text-align:justify"><strong>Article 6. Rétractation </strong></p>
<p style="text-align:justify">En vertu de l’article L121-20 du Code de la consommation, l’utilisateur dispose d'un délai de quatorze jours ouvrables à compter de la livraison de leur commande pour exercer son droit de rétractation et ainsi faire retour du produit au vendeur pour échange ou remboursement sans pénalité, à l’exception des frais de retour.</p>
<p style="text-align:justify"><strong>Article 7. Livraison </strong></p>
<p style="text-align:justify">Les livraisons sont faites à l’adresse indiquée sur le bon de commande qui ne peut être que dans la zone géographique convenue. Les commandes sont effectuées par La Poste via COLISSIMO, service de livraison avec suivi, remise sans signature. Les délais de livraison ne sont donnés qu’à titre indicatif ; si ceux-ci dépassent trente jours à compter de la commande, le contrat de vente pourra être résilié et l’utilisateur remboursé. La société Le Bon Troc pourra fournir par e-mail à l’utilisateur le numéro de suivi de son colis. L’utilisateur est livré à son domicile par son facteur. En cas d’absence de l’utilisateur, il recevra un avis de passage de son facteur, ce qui lui permet de retirer les produits commandés au bureau de Poste le plus proche, pendant un délai indiqué par les services postaux. Les risques liés au transport sont à la charge de l'acquéreur à compter du moment où les articles quittent les locaux de la société Le Bon Troc. L’utilisateur est tenu de vérifier en présence du préposé de La Poste ou du livreur, l’état de l’emballage de la marchandise et son contenu à la livraison. En cas de dommage pendant le transport, toute protestation doit être effectuée auprès du transporteur dans un délai de trois jours à compter de la livraison.</p>
<p style="text-align:justify"><strong>Article 8. Garantie </strong></p>
<p style="text-align:justify">Tous les produits fournis par la société Le Bon Troc bénéficient de la garantie légale prévue par les articles 1641 et suivants du Code civil. En cas de non conformité d’un produit vendu, il pourra être retourné à la société Le Bon Troc qui le reprendra, l’échangera ou le remboursera. Toutes les réclamations, demandes d’échange ou de remboursement doivent s’effectuer par voie postale à l’adresse suivante : Le Bon Troc, 25 rue Mademoiselle, 75015, Paris, France, dans un délai de trente jours après livraison.</p>
<p style="text-align:justify">A<strong>rticle 9. Responsabilité </strong></p>
<p style="text-align:justify">La société Le Bon Troc, dans le processus de vente à distance, n’est tenue que par une obligation de moyens. Sa responsabilité ne pourra être engagée pour un dommage résultant de l’utilisation du réseau Internet tel que perte de données, intrusion, virus, rupture du service, ou autres problèmes involontaires.</p>
<p style="text-align:justify"><strong>Article 10. Propriété intellectuelle </strong></p>
<p style="text-align:justify">Tous les éléments du site Le Bon Troc, www.lebontroc.com sont et restent la propriété intellectuelle et exclusive de la société Le Bon Troc. Personne n’est autorisé à reproduire, exploiter, ou utiliser à quelque titre que ce soit, même partiellement, des éléments du site qu’ils soient sous forme de photo, logo, visuel ou texte.</p>
<p style="text-align:justify"><strong>Article 11. Données à caractère personnel</strong></p>
<p style="text-align:justify">La société Le Bon Troc s'engage à préserver la confidentialité des informations fournies par l’utilisateur, qu'il serait amené à transmettre pour l'utilisation de certains services. Toute information le concernant est soumise aux dispositions de la loi n° 78-17 du 6 janvier 1978. A ce titre, l'internaute dispose d'un droit d'accès, de modification et de suppression des informations le concernant. Il peut en faire la demande à tout moment par courrier à l’adresse suivante : Le Bon Troc, 25 rue Mademoiselle, 75015, Paris, France.</p>
<p style="text-align:justify"><strong>Article 12. Règlement des litiges </strong></p>
<p style="text-align:justify">Les présentes conditions d'utilisations à distance sont soumises à la loi française. Pour tous litiges ou contentieux, le Tribunal compétent sera celui de Paris.</p>

<?php 
require_once('inc/bas.inc.php');
